### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by Maikon** [Katerina-codes/hangman_game#3]
One example is [here](https://github.com/Katerina-codes/hangman_game/blob/master/spec/display_spec.rb#L67). Look for other places where dead code exists and remove it.

**Comment by Katerina-codes** [comment]
Fixed: https://github.com/Katerina-codes/hangman_game/commit/c1e8484b7d63de14d6947010d9315a9504189db1

Sorry @Maikon , I already committed the changes.
